### ISSUE TITLE
Add new git tag for contao 4.4 (contao-manager)

### ISSUE THREAD

**Issue by Ma3xl3** [psi-4ward/boxes4ward#26]
First, thx for your great plugin.
Is it possible to add a new git tag (e.g. 2.1.0) to your newest commit so that you can install your extension without the additional version entry of "master-dev" via contao manager?

**Comment by psi-4ward** [comment]
@baumannsven ;)

**Comment by dmolineus** [comment]
@psi-4ward Any chance to get a new release this month? If you're out of time I'm willing to support you maintaining this package.

**Comment by psi-4ward** [comment]
@dmolineus see my skype message, added you as collab

**Comment by jankout** [comment]
I cannot install your extension because of following issue. 

```
  Problem 1
    - Conclusion: remove contao/calendar-bundle 4.5.3
    - Conclusion: don't install contao/calendar-bundle 4.5.3
    - psi/boxes4ward 2.0.1 requires contao/core >=3.1,<3.3 -> satisfiable by contao/core[3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.1.5, 3.2.0, 3.2.1, 3.2.10, 3.2.11, 3.2.12, 3.2.13, 3.2.14, 3.2.15, 3.2.16, 3.2.17, 3.2.18, 3.2.19, 3.2.2, 3.2.20, 3.2.21, 3.2.3, 3.2.4, 3.2.5, 3.2.6, 3.2.7, 3.2.8, 3.2.9].
    - psi/boxes4ward 2.0.2 requires contao/core >=3.1,<3.3 -> satisfiable by contao/core[3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.1.5, 3.2.0, 3.2.1, 3.2.10, 3.2.11, 3.2.12, 3.2.13, 3.2.14, 3.2.15, 3.2.16, 3.2.17, 3.2.18, 3.2.19, 3.2.2, 3.2.20, 3.2.21, 3.2.3, 3.2.4, 3.2.5, 3.2.6, 3.2.7, 3.2.8, 3.2.9].
    - psi/boxes4ward 2.0.3 requires contao/core >=3.1,<3.3 -> satisfiable by contao/core[3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.1.5, 3.2.0, 3.2.1, 3.2.10, 3.2.11, 3.2.12, 3.2.13, 3.2.14, 3.2.15, 3.2.16, 3.2.17, 3.2.18, 3.2.19, 3.2.2, 3.2.20, 3.2.21, 3.2.3, 3.2.4, 3.2.5, 3.2.6, 3.2.7, 3.2.8, 3.2.9].
    - psi/boxes4ward 2.0.4 requires contao/core >=3.1,<3.4 -> satisfiable by contao/core[3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.1.5, 3.2.0, 3.2.1, 3.2.10, 3.2.11, 3.2.12, 3.2.13, 3.2.14, 3.2.15, 3.2.16, 3.2.17, 3.2.18, 3.2.19, 3.2.2, 3.2.20, 3.2.21, 3.2.3, 3.2.4, 3.2.5, 3.2.6, 3.2.7, 3.2.8, 3.2.9, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.3.4, 3.3.5, 3.3.6, 3.3.7].
    - psi/boxes4ward 2.0.5 requires contao/core >=3.1,<4 -> satisfiable by contao/core[3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.1.5, 3.2.0, 3.2.1, 3.2.10, 3.2.11, 3.2.12, 3.2.13, 3.2.14, 3.2.15, 3.2.16, 3.2.17, 3.2.18, 3.2.19, 3.2.2, 3.2.20, 3.2.21, 3.2.3, 3.2.4, 3.2.5, 3.2.6, 3.2.7, 3.2.8, 3.2.9, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.3.4, 3.3.5, 3.3.6, 3.3.7, 3.4.0, 3.4.1, 3.4.2, 3.4.3, 3.4.4, 3.4.5, 3.5.0, 3.5.1, 3.5.10, 3.5.11, 3.5.12, 3.5.13, 3.5.14, 3.5.15, 3.5.16, 3.5.17, 3.5.18, 3.5.19, 3.5.2, 3.5.20, 3.5.21, 3.5.22, 3.5.23, 3.5.24, 3.5.25, 3.5.26, 3.5.27, 3.5.28, 3.5.29, 3.5.3, 3.5.30, 3.5.31, 3.5.4, 3.5.5, 3.5.6, 3.5.7, 3.5.8, 3.5.9].
    - contao/core 3.1.0 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.1.1 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.1.2 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.1.3 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.1.4 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.1.5 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.2.0 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.2.1 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.2.10 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.2.11 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.2.12 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.2.13 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.2.14 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.2.15 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.2.16 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.2.17 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.2.18 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.2.19 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.2.2 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.2.20 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.2.21 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.2.3 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.2.4 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.2.5 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.2.6 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.2.7 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.2.8 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.2.9 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.3.0 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.3.1 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.3.2 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.3.3 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.3.4 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.3.5 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.3.6 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.3.7 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.4.0 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.4.1 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.4.2 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.4.3 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.4.4 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.4.5 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.5.0 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.5.1 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.5.10 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.5.11 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.5.12 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.5.13 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.5.14 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.5.15 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.5.16 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.5.17 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.5.18 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.5.19 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.5.2 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.5.20 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.5.21 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.5.22 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.5.23 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.5.24 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.5.25 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.5.26 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.5.27 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.5.28 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.5.29 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.5.3 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.5.30 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.5.31 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.5.4 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.5.5 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.5.6 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.5.7 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.5.8 conflicts with contao/calendar-bundle[4.5.3].
    - contao/core 3.5.9 conflicts with contao/calendar-bundle[4.5.3].
    - Installation request for contao/calendar-bundle (locked at 4.5.3, required as ^4.5) -> satisfiable by contao/calendar-bundle[4.5.3].
    - Installation request for psi/boxes4ward ^2.0 -> satisfiable by psi/boxes4ward[2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5].

<warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>

Installation failed, reverting /www/htdocs/w017add7/bro198.net/composer.json to its original content.
--------------------------------------------------------
Exception occured: Error: command exit code was 2
#0 phar:///www/htdocs/w017add7/bro198.net/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(166): Tenside\Core\Task\Composer\AbstractComposerCommandTask->executeCommand(Object(Tenside\Core\Task\Composer\WrappedCommand\RequireCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#1 phar:///www/htdocs/w017add7/bro198.net/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Task.php(173): Tenside\Core\Task\Composer\AbstractComposerCommandTask->doPerform()
#2 phar:///www/htdocs/w017add7/bro198.net/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Runner.php(89): Tenside\Core\Task\Task->perform('/www/htdocs/w01...')
#3 phar:///www/htdocs/w017add7/bro198.net/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(82): Tenside\Core\Task\Runner->run('/www/htdocs/w01...')
#4 phar:///www/htdocs/w017add7/bro198.net/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(240): Tenside\CoreBundle\Command\RunTaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 phar:///www/htdocs/w017add7/bro198.net/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(61): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///www/htdocs/w017add7/bro198.net/web/contao-manager.phar.php/vendor/symfony/console/Application.php(875): Tenside\CoreBundle\Command\RunTaskCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///www/htdocs/w017add7/bro198.net/web/contao-manager.phar.php/vendor/symfony/console/Application.php(215): Symfony\Component\Console\Application->doRunCommand(Object(Tenside\CoreBundle\Command\RunTaskCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///www/htdocs/w017add7/bro198.net/web/contao-manager.phar.php/api/ApiApplication.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///www/htdocs/w017add7/bro198.net/web/contao-manager.phar.php/vendor/symfony/console/Application.php(122): Contao\ManagerApi\ApiApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///www/htdocs/w017add7/bro198.net/web/contao-manager.phar.php/api/console(83): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /www/htdocs/w017add7/bro198.net/web/contao-manager.phar.php(55): require('phar:///www/htd...')
#12 {main}
Chained exception: Error: command exit code was 2
#0 phar:///www/htdocs/w017add7/bro198.net/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(166): Tenside\Core\Task\Composer\AbstractComposerCommandTask->executeCommand(Object(Tenside\Core\Task\Composer\WrappedCommand\RequireCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#1 phar:///www/htdocs/w017add7/bro198.net/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Task.php(173): Tenside\Core\Task\Composer\AbstractComposerCommandTask->doPerform()
#2 phar:///www/htdocs/w017add7/bro198.net/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Runner.php(89): Tenside\Core\Task\Task->perform('/www/htdocs/w01...')
#3 phar:///www/htdocs/w017add7/bro198.net/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(82): Tenside\Core\Task\Runner->run('/www/htdocs/w01...')
#4 phar:///www/htdocs/w017add7/bro198.net/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(240): Tenside\CoreBundle\Command\RunTaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 phar:///www/htdocs/w017add7/bro198.net/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(61): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///www/htdocs/w017add7/bro198.net/web/contao-manager.phar.php/vendor/symfony/console/Application.php(875): Tenside\CoreBundle\Command\RunTaskCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///www/htdocs/w017add7/bro198.net/web/contao-manager.phar.php/vendor/symfony/console/Application.php(215): Symfony\Component\Console\Application->doRunCommand(Object(Tenside\CoreBundle\Command\RunTaskCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///www/htdocs/w017add7/bro198.net/web/contao-manager.phar.php/api/ApiApplication.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///www/htdocs/w017add7/bro198.net/web/contao-manager.phar.php/vendor/symfony/console/Application.php(122): Contao\ManagerApi\ApiApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///www/htdocs/w017add7/bro198.net/web/contao-manager.phar.php/api/console(83): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /www/htdocs/w017add7/bro198.net/web/contao-manager.phar.php(55): require('phar:///www/htd...')
#12 {main}
--------------------------------------------------------


Process terminated with exit code 1
Reason: General error
```

**Comment by Ma3xl3** [comment]
@jankout it is working when you change the version to "master-dev"

![image](https://user-images.githubusercontent.com/1608186/36271187-28bf5296-127e-11e8-8636-7f8aaffa2b1f.png)

But that´s not the best Solution. It would be very helpful if we get a new tag for the current master-dev version.
